config/routes.rb
Rails.application.routes.draw do
  get root :to => 'books#top' 
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as:'edit_book'
  patch 'books/:id' => 'books#update', as:'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def top
  end
  
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render action: :index
    end
  end

  def show
    @book =  Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render action: :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing Book</h1>
<!--<%= form_with model:@book, local:true do |f| %>-->
<!--  <% if @book.errors.any? %>-->
<!--    <div class="error_explanation">-->
<!--      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>-->
<!--      <ul>-->
<!--        <% @book.errors.full_messages.each do |message| %>-->
<!--          <li><%= message %></li>-->
<!--        <% end %>-->
<!--      </ul>-->
<!--    </div>-->
<!--  <% end %> -->
<!--  <p>Title</p>-->
<!--  <%= f.text_field :title %>-->
<!--  <p>Body</p>-->
<!--  <%= f.text_area :body %>-->
<!--  <%= f.submit 'Update Book' %>-->
<!--<% end %>-->

<%= form_with model:@book, local:true do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <div class="error-field">
      <label>Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="error-field">
      <label>Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.submit 'Create Book' %>
    </div>
  <% else %>
    <div class="field">
      <label>Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <label>Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.submit 'Update Book' %>
    </div>
  <% end %>  
<% end %>

<%= link_to 'Show', book_path(@book) %>|<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p> 
<h1>Books</h1>
<table>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %>　</td>
        <td><%= book.body %>　</td>
        <td>
          <%= link_to 'Show', book_path(book) %>　
          <%= link_to 'Edit', edit_book_path(book) %>　
          <%= link_to 'Destroy', destroy_book_path(book), method: :delete, data: { confirm: 'Are you sure？' } %>
        </td>
      </tr>
    <% end %>
</table>
<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <div class="error-field">
      <label>Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="error-field">
      <label>Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.submit 'Create Book' %>
    </div>
  <% else %>
    <div class="field">
      <label>Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <label>Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>  
<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong>Title:</strong><%= @book.title %></p>
<p><strong>Body:</strong><%= @book.body %></p>
<%= link_to 'Edit', edit_book_path(@book) %>|<%= link_to 'back', books_path %>

app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>
  <p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます </p>
  <p><%= link_to "start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>